swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transaction/{idTransaction}:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Edit a comment
      description: Allow the edit of a comment on a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: idTransaction
          in: path
          required: true
          type: integer
          description: ID transaction
        - name: transaction
          in: body
          description: Comment payload.
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "201":
          description: Comment edited successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get a specific transaction
      description: Get information on a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: idTransaction
          in: path
          required: true
          type: integer
          description: ID transaction
      produces:
        - application/json
      responses:
        "200":
          description: Get a specific transaction successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all transactions
      description: Get all transactions
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Get all transactions successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      category:
        type: string
        example: "Alimentation"
      note:
        type: string
        example: "Ceci est une note"
  TransactionDetail:
    type: object
    properties:
      id:
        type: integer
        example: 1
      category:
        type: string
        example: "Alimentation"
      note:
        type: string
        example: "Ceci est une note"
      date:
        type: string
        example: "2019-01-01T00:00:00.000Z"
      amount:
        type: number
        example: "28.00"
  Transactions:
    type: array
    items:
      $ref: "#/definitions/TransactionDetail"
